version: "3.3"
services:
  sensor-backend:
    command: npm run debug
    volumes:
      - ./dist:/opt/app/dist
      - ./node_modules:/opt/app/node_modules
      - ./uploads:/opt/app/uploads
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - message-broker
      - sensors-publisher

  message-broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

  sensors-publisher:
    image: sensors-publisher
